const PromptDatabaseBasic = [
    {p: "Hello", a: "안녕하세요", d: "Standard greeting in Korean.", c: "", r: "annyeonghaseyo"},
    {p: "Thank you", a: "감사합니다", d: "Expressing gratitude in Korean.", c: "", r: "gamsahamnida"},
    {p: "Yes", a: "네", d: "Simple affirmative response.", c: "", r: "ne"},
    {p: "No", a: "아니요", d: "Simple negative response.", c: "", r: "aniyo"},
    {p: "I'm sorry", a: "미안합니다", d: "Apologizing in Korean.", c: "", r: "mianhamnida"},
    {p: "Love", a: "사랑", d: "Expressing affection or deep care.", c: "", r: "sarang"},
    {p: "Friend", a: "친구", d: "Someone with whom one shares a bond of mutual affection.", c: "", r: "chingu"},
    {p: "Bag", a: "가방", d: "Container for carrying personal items.", c: "", r: "gabang"},
    {p: "School", a: "학교", d: "Place of education.", c: "", r: "hakgyo"},
    {p: "Food", a: "음식", d: "General term for sustenance.", c: "", r: "eumsik"},
    {p: "Water", a: "물", d: "Essential liquid for hydration.", c: "", r: "mul"},
    {p: "Coffee", a: "커피", d: "Popular beverage made from roasted coffee beans.", c: "", r: "keopi"},
    {p: "Tea", a: "차", d: "Hot or cold beverage made by infusing dried leaves in water.", c: "", r: "cha"},
    {p: "Apple", a: "사과", d: "Fruit with a red or green skin and crisp white flesh.", c: "", r: "sagwa"},
    {p: "Cat", a: "고양이", d: "Small domesticated carnivorous mammal.", c: "", r: "goyangi"},
    {p: "Dog", a: "개", d: "Domesticated carnivorous mammal.", c: "", r: "gae"},
    {p: "Book", a: "책", d: "Written or printed work consisting of pages.", c: "", r: "chaek"},
    {p: "Time", a: "시간", d: "Indication of when an event occurs.", c: "", r: "sigan"},
    {p: "Weather", a: "날씨", d: "Conditions of the atmosphere at a particular time and place.", c: "", r: "nalssi"},
    {p: "Like", a: "좋아요", d: "Expressing positive feelings or preferences.", c: "", r: "joayo"},
    {p: "Dislike", a: "싫어요", d: "Expressing negative feelings or preferences.", c: "", r: "sireoyo"},
    {p: "Where", a: "어디", d: "Asking about a location or place.", c: "", r: "eodi"},
    {p: "Here", a: "여기", d: "Indicating a location or place near the speaker.", c: "", r: "yeogi"},
    {p: "There", a: "거기", d: "Indicating a location or place near the listener.", c: "", r: "geogi"},
    {p: "When", a: "언제", d: "Asking about a specific time or occasion.", c: "", r: "eonje"},
    {p: "Who", a: "누구", d: "Asking about the identity of a person.", c: "", r: "nugu"},
    {p: "What", a: "뭐", d: "Asking about the identity or nature of something.", c: "", r: "mwo"},
    {p: "Why", a: "왜", d: "Asking for the reason or cause of something.", c: "", r: "wae"},
    {p: "How", a: "어떻게", d: "Asking about the manner or method of doing something.", c: "", r: "eotteoke"},
    {p: "Delicious", a: "맛있어요", d: "Expressing enjoyment of food or drink.", c: "", r: "masisseoyo"},
    {p: "This", a: "이", d: "Indicating something near the speaker.", c: "", r: "i"},
    {p: "That", a: "그", d: "Indicating something near the listener.", c: "", r: "geu"},
    {p: "That (over there)", a: "저", d: "Indicating something far from both speaker and listener.", c: "", r: "jeo"},
    {p: "Beautiful", a: "아름다운", d: "Having beauty or aesthetic appeal.", c: "", r: "areumdaun"},
    {p: "Big", a: "큰", d: "Of considerable size.", c: "", r: "keun"},
    {p: "Small", a: "작은", d: "Of limited size or magnitude.", c: "", r: "jageun"},
    {p: "High", a: "높은", d: "Having a great vertical extent.", c: "", r: "nopheun"},
    {p: "Low", a: "낮은", d: "Having little height.", c: "", r: "nopheun"},
    {p: "New", a: "새", d: "Recently made or created.", c: "", r: "sae"},
    {p: "Old", a: "오래된", d: "Having lived for a long time.", c: "", r: "oraedoen"},
    {p: "Fast", a: "빠른", d: "Moving or capable of moving quickly.", c: "", r: "ppareun"},
    {p: "Slow", a: "느린", d: "Moving or operating at a low speed.", c: "", r: "neurin"},
    {p: "Good", a: "좋은", d: "Having favorable qualities.", c: "", r: "joeun"},
    {p: "Bad", a: "나쁜", d: "Having undesirable or negative qualities.", c: "", r: "nappeun"},
    {p: "Happy", a: "행복한", d: "Feeling or showing pleasure or contentment.", c: "", r: "haengbokhan"},
    {p: "Sad", a: "슬픈", d: "Feeling or showing sorrow or unhappiness.", c: "", r: "seulpeun"},
    {p: "Cold", a: "추운", d: "Having a low temperature.", c: "", r: "chuun"},
    {p: "Hot", a: "더운", d: "Having a high temperature.", c: "", r: "deoun"},
    {p: "Joyful", a: "기쁜", d: "Feeling or expressing joy.", c: "", r: "gippeun"},
    {p: "Sorrowful", a: "슬픈", d: "Feeling or expressing sadness.", c: "", r: "seulpeun"},
    {p: "True", a: "진실한", d: "In accordance with fact or reality.", c: "", r: "jinsilhan"},
    {p: "False", a: "거짓말한", d: "Not in accordance with fact or reality.", c: "", r: "geojitmalhan"},
    {p: "Something", a: "무엇", d: "A thing that is unspecified or unknown.", c: "", r: "mueos"},
    {p: "Nothing", a: "아무것도", d: "Not anything; no single thing.", c: "", r: "amugeotdo"},
    {p: "Everything", a: "모든", d: "All things; all possible options.", c: "", r: "modeun"},
    {p: "Many", a: "많은", d: "A large number or amount of something.", c: "", r: "manheun"},
    {p: "Few", a: "적은", d: "Not many; a small number of something.", c: "", r: "jeogeun"},
    {p: "Easy", a: "쉬운", d: "Not difficult; requiring little effort.", c: "", r: "swiun"},
    {p: "Difficult", a: "어려운", d: "Needing much effort or skill to accomplish.", c: "", r: "eoryeoun"},
    {p: "Near", a: "가까운", d: "Close to in distance or time.", c: "", r: "gakkao-un"},
    {p: "Far", a: "먼", d: "At a great distance from the observer.", c: "", r: "meon"},
    {p: "Yet", a: "아직", d: "Up to the present or a specified time.", c: "", r: "ajik"},
    {p: "Already", a: "이미", d: "Before or by now or the time in question.", c: "", r: "imi"},
    {p: "Now", a: "이제", d: "At the present time or moment.", c: "", r: "ije"},
    {p: "Later", a: "나중에", d: "At a time subsequent to the present or an anticipated event.", c: "", r: "najunge"},
    {p: "Always", a: "항상", d: "At all times; on all occasions.", c: "", r: "hangsang"},
    {p: "Sometimes", a: "종종", d: "On certain occasions or in certain cases but not always.", c: "", r: "jongjong"},
    {p: "Occasionally", a: "가끔", d: "From time to time; now and then.", c: "", r: "gakkeum"},
    {p: "Korea", a: "한국", d: "Country in East Asia.", c: "", r: "hanguk"},
    {p: "America", a: "미국", d: "Country in North America.", c: "", r: "mi-guk"},
    {p: "Japan", a: "일본", d: "Country in East Asia.", c: "", r: "ilbon"},
    {p: "China", a: "중국", d: "Country in East Asia.", c: "", r: "jungguk"},
    {p: "English", a: "영어", d: "West Germanic language widely spoken worldwide.", c: "", r: "yeong-eo"},
    {p: "Korean (language)", a: "한국어", d: "Language spoken in Korea.", c: "", r: "hangugeo"},
    {p: "Chicken", a: "치킨", d: "Popular meat from the domestic fowl.", c: "", r: "chikin"},
    {p: "Homework", a: "숙제", d: "Schoolwork assigned to be done outside the classroom.", c: "", r: "sukje"},
    {p: "Travel", a: "여행", d: "Journeying from one place to another.", c: "", r: "yeohaeng"},
    {p: "Exercise", a: "운동", d: "Physical activity done to maintain health.", c: "", r: "undong"},
    {p: "Weekend", a: "주말", d: "Period of leisure time between the end of the working week and the start of the next.", c: "", r: "jumal"},
    {p: "Movie", a: "영화", d: "Form of entertainment that tells stories through images and sounds.", c: "", r: "yeonghwa"},
    {p: "Music", a: "음악", d: "Art form consisting of sound and silence.", c: "", r: "eumak"},
    {p: "Dance", a: "춤", d: "Series of movements performed to music.", c: "", r: "chum"},
    {p: "Study", a: "공부", d: "The act of acquiring knowledge or skills.", c: "", r: "gongbu"},
    {p: "Shopping", a: "쇼핑", d: "Purchasing goods from stores.", c: "", r: "syoping"},
    {p: "Photo", a: "사진", d: "Image captured by a camera.", c: "", r: "sajin"},
    {p: "Family", a: "가족", d: "Group consisting of parents and their children.", c: "", r: "gajok"},
    {p: "House/Home", a: "집", d: "Building where one lives.", c: "", r: "jip"},
    {p: "Song", a: "노래", d: "Musical composition.", c: "", r: "nolae"},
    {p: "Friends", a: "친구들", d: "Plural form of friend.", c: "", r: "chingu-deul"},
    {p: "Practice", a: "연습", d: "Repetition of an activity to improve skill.", c: "", r: "yeonseup"},
    {p: "Cooking", a: "요리", d: "The practice or skill of preparing food.", c: "", r: "yori"},
    {p: "Vacation", a: "방학", d: "A period of time devoted to leisure.", c: "", r: "banghak"},
    {p: "Park", a: "공원", d: "Public garden or area of land.", c: "", r: "gongwon"},
    {p: "Flower", a: "꽃", d: "The seed-bearing part of a plant.", c: "", r: "kkot"},
    {p: "Color", a: "색", d: "Visual perception.", c: "", r: "saek"},
    {p: "Number", a: "숫자", d: "An arithmetical value.", c: "", r: "sujja"},
    {p: "Animal", a: "동물", d: "Living organism that feeds on organic matter.", c: "", r: "dongmul"},
    {p: "Sound", a: "소리", d: "Vibrations that travel through the air.", c: "", r: "sori"},
    {p: "Problem", a: "문제", d: "A matter or situation regarded as unwelcome or harmful.", c: "", r: "munje"},
    {p: "Answer", a: "답", d: "A solution to a problem or question.", c: "", r: "dap"}
]

PromptDatabaseSejongVocab = [
    {p: "Engagement", a: "약혼", d: "The official start of 'We're in this together' club.", c: "", r: "yakhon"},
    {p: "Vocabulary", a: "어휘", d: "The stuff you pretend to know during a test.", c: "", r: "eohwi"},
    {p: "Index", a: "색인", d: "A list of excuses for not reading the whole book.", c: "", r: "saegin"},
    {p: "Chilly", a: "추운", d: "When your fridge gets jealous of the outdoors.", c: "", r: "chuun"},
    {p: "China", a: "중국", d: "Where all your ceramic mugs come from.", c: "", r: "jungguk"},
    {p: "Class", a: "수업", d: "A place where sleep is just a blink away.", c: "", r: "sueob"},
    {p: "Every day", a: "매일", d: "The one thing that always happens, every single day.", c: "", r: "maeil"},
    {p: "Exercise", a: "운동", d: "The art of convincing yourself to sweat.", c: "", r: "undong"},
    {p: "Classroom", a: "교실", d: "Where the real drama happens, besides K-dramas.", c: "", r: "gyosil"},
    {p: "Clean", a: "깨끗한", d: "What your room becomes when guests are expected.", c: "", r: "kkaekkeuthan"},
    {p: "Clock", a: "시계", d: "A device that has a grudge against procrastination.", c: "", r: "sigye"},
    {p: "Clothes", a: "옷", d: "Things you wear to pretend you have your life together.", c: "", r: "ot"},
    {p: "Cloudy", a: "흐린", d: "The sky's version of 'I'm not in the mood.'", c: "", r: "heurin"},
    {p: "Coffee", a: "커피", d: "The liquid that turns 'leave me alone' into 'good morning.'", c: "", r: "keopi"},
    {p: "Cold", a: "추운", d: "Nature's way of telling you to snuggle up.", c: "", r: "chuun"},
    {p: "College student", a: "대학생", d: "The sleep-deprived species known for surviving on ramen.", c: "", r: "daehaksaeng"},
    {p: "Come", a: "오다", d: "When plans finally decide to show up.", c: "", r: "oda"},
    {p: "Commute", a: "통근", d: "The daily race against time and traffic.", c: "", r: "tonggeun"},
    {p: "Company", a: "회사", d: "Where your weekdays go to feel productive.", c: "", r: "hoesa"},
    {p: "Computer", a: "컴퓨터", d: "The modern-day magic box for all your procrastination needs.", c: "", r: "keompyuteo"},
    {p: "Concert", a: "콘서트", d: "Where music turns strangers into a chorus.", c: "", r: "konseoteu"},
    {p: "Content", a: "내용", d: "The reason you scrolled all the way down.", c: "", r: "naeyong"},
    {p: "Convenience store", a: "편의점", d: "The saving grace at 2 AM when hunger strikes.", c: "", r: "pyeonuijeom"},
    {p: "Cook", a: "요리사", d: "The wizard behind the kitchen curtains.", c: "", r: "yorisa"},
    {p: "Fall", a: "가을", d: "When nature decides to redecorate in warm hues.", c: "", r: "gaeul"},
    {p: "Father", a: "아버지", d: "The OG dad jokes supplier.", c: "", r: "abeoji"},
    {p: "February", a: "2월", d: "The shortest month with the biggest Valentine's bill.", c: "", r: "iyweol"},
    {p: "Fifteen", a: "십오", d: "The age of confusion between being a kid and a teenager.", c: "", r: "sip-o"},
    {p: "Fifty", a: "오십", d: "When life begins at 50, and so does the fun.", c: "", r: "osip"},
    {p: "Fishing", a: "낚시", d: "The art of fooling fish into thinking you're a friend.", c: "", r: "naksi"},
    {p: "Alphabetical order", a: "알파벳 순서", d: "The library's way of keeping chaos in check.", c: "", r: "alpabes sunseo"},
    {p: "Floor", a: "바닥", d: "The unsung hero of our daily adventures.", c: "", r: "badak"},
    {p: "Flower", a: "꽃", d: "Nature's way of saying 'smile, it's free.'", c: "", r: "kkot"},
    {p: "Food", a: "음식", d: "The reason you go to a restaurant instead of the gym.", c: "", r: "eumsik"},
    {p: "Forty", a: "사십", d: "When you realize life's just getting started at 40.", c: "", r: "sasip"},
    {p: "Four seasons", a: "사계절", d: "Nature's wardrobe change, four times a year.", c: "", r: "sagyejeol"},
    {p: "Four", a: "사", d: "The number of fingers we use for counting.", c: "", r: "sa"},
    {p: "Fourteen", a: "십사", d: "The age of 'almost there, but not quite.'", c: "", r: "sipsa"},
    {p: "France", a: "프랑스", d: "Where cheese and wine have a romantic rendezvous.", c: "", r: "peurangseu"},
    {p: "Friend", a: "친구", d: "The personal cheerleader in life's marathon.", c: "", r: "chingu"},
    {p: "Fruit", a: "과일", d: "Nature's sweet rebellion against junk food.", c: "", r: "gwail"},
    {p: "Fun", a: "재미있는", d: "The excuse you use for procrastination.", c: "", r: "jaemiinneun"},
    {p: "Gear", a: "장비", d: "The superhero outfit for your hobbies.", c: "", r: "jangbi"},
    {p: "Cool", a: "시원한", d: "The official temperature of chill vibes.", c: "", r: "siwonhan"},
    {p: "Cosmetics", a: "화장품", d: "The magic wand for the 8 AM transformation.", c: "", r: "hwajangpum"},
    {p: "Country", a: "나라", d: "Where patriotism and passport meet.", c: "", r: "nara"},
    {p: "Begin", a: "시작하다", d: "The moment when 'someday' becomes 'today.'", c: "", r: "sijakhada"},
    {p: "Behind", a: "뒤에", d: "Where surprises and shadows lurk.", c: "", r: "dwie"},
    {p: "Between", a: "사이에", d: "The space where decisions hang in the balance.", c: "", r: "saie"},
    {p: "Beverage", a: "음료", d: "Liquid courage in a cup.", c: "", r: "eumryo"},
    {p: "Bicycle", a: "자전거", d: "The two-wheeled escape from traffic.", c: "", r: "jajeongeo"},
    {p: "Birthday", a: "생일", d: "The annual reminder of your 'specialness.'", c: "", r: "saengil"},
    {p: "Blackboard", a: "칠판", d: "Where dust meets wisdom.", c: "", r: "chilpan"},
    {p: "Blow", a: "불다", d: "The human version of wind power.", c: "", r: "bunda"},
    {p: "Book", a: "책", d: "The ultimate time machine.", c: "", r: "chaek"},
    {p: "Bottle", a: "병", d: "The ship that carries your liquid treasure.", c: "", r: "byeong"},
    {p: "Boy", a: "소년", d: "A human whirlwind of mischief and wonder.", c: "", r: "sonyeon"},
    {p: "Bread", a: "빵", d: "The edible hug that fits in your hand.", c: "", r: "ppang"},
    {p: "Bulgogi", a: "불고기", d: "The Korean BBQ that converts vegetarians.", c: "", r: "bulgogi"},
    {p: "Bus", a: "버스", d: "The mobile waiting room for life's adventures.", c: "", r: "beoseu"},
    {p: "Busan", a: "부산", d: "Where seafood and sea breezes reign supreme.", c: "", r: "busan"},
    {p: "Business", a: "비즈니스", d: "The adult version of playing house.", c: "", r: "bijeuniseu"},
    {p: "A little", a: "조금", d: "The portion size that never satisfies.", c: "", r: "jogeum"},
    {p: "A lot", a: "많이", d: "The serving size that always surprises.", c: "", r: "manhi"},
    {p: "Activity", a: "활동", d: "The organized chaos of being productive.", c: "", r: "hwaldong"},
    {p: "Address", a: "주소", d: "Where GPS and hope intersect.", c: "", r: "juso"},
    {p: "Afternoon", a: "오후", d: "The siesta before the second wind kicks in.", c: "", r: "ohu"},
    {p: "All", a: "모두", d: "The elusive concept of 'everyone.'", c: "", r: "modu"},
    {p: "Amusement park", a: "놀이 공원", d: "Where gravity takes a vacation.", c: "", r: "noli gongwon"},
    {p: "Cup", a: "컵", d: "The vessel that holds your morning sanity.", c: "", r: "keop"},
    {p: "Date", a: "날짜", d: "The tiny reminder of your existence on the timeline.", c: "", r: "nalja"},
    {p: "Day", a: "일", d: "The unit of time you try to fit a lifetime into.", c: "", r: "il"},
    {p: "December", a: "12월", d: "When holiday spirit meets shopping frenzy.", c: "", r: "sibweol"},
    {p: "Department store", a: "백화점", d: "The labyrinth where wallets go to die.", c: "", r: "baekhwajeom"},
    {p: "Desk", a: "책상", d: "The island of productivity in the sea of chaos.", c: "", r: "chaeksang"},
    {p: "Different", a: "다른", d: "The spice of life's smorgasbord.", c: "", r: "dareun"},
    {p: "Difficult", a: "어려운", d: "The VIP section of life's obstacle course.", c: "", r: "eoryeoun"},
    {p: "Do", a: "하다", d: "The universal solution to procrastination.", c: "", r: "hada"},
    {p: "Doctor", a: "의사", d: "The human repair shop.", c: "", r: "uisa"},
    {p: "Drink", a: "마시다", d: "The liquid version of 'I got this.'", c: "", r: "masida"},
    {p: "And", a: "그리고", d: "The glue that holds sentences together.", c: "", r: "geurigo"},
    {p: "Answer", a: "대답", d: "The whisper in the silence of questions.", c: "", r: "daedap"},
    {p: "Apple", a: "사과", d: "The forbidden fruit that keeps the doctor busy.", c: "", r: "sagwa"},
    {p: "Appointment", a: "약속", d: "Where time and commitment shake hands.", c: "", r: "yaksok"},
    {p: "April", a: "4월", d: "When pranks and showers are in season.", c: "", r: "sawol"},
    {p: "August", a: "8월", d: "When summer's lease is almost up.", c: "", r: "palweol"},
    {p: "Autumn foliage", a: "가을 단풍", d: "Nature's canvas of warm hues.", c: "", r: "gaeul danpung"},
    {p: "Busy", a: "바쁜", d: "The badge of honor for the overcommitted.", c: "", r: "bappeun"},
    {p: "Bag", a: "가방", d: "The portable universe for all your stuff.", c: "", r: "gabang"},
    {p: "Ball", a: "공", d: "The roundest way to make friends.", c: "", r: "gong"},
    {p: "Banana", a: "바나나", d: "Nature's original snack pack.", c: "", r: "banana"},
    {p: "Basement", a: "지하실", d: "Where spiders and forgotten treasures reside.", c: "", r: "jihasil"},
    {p: "Basketball", a: "농구", d: "The symphony of hoops and dreams.", c: "", r: "nonggu"},
    {p: "But", a: "하지만", d: "The bridge between 'yes' and 'no.'", c: "", r: "hajiman"},
    {p: "Buy", a: "사다", d: "The adult version of 'treat yo'self.'", c: "", r: "sada"},
    {p: "Café", a: "카페", d: "The fueling station for caffeine and gossip.", c: "", r: "kafe"},
    {p: "Cake", a: "케이크", d: "The sweet reward for surviving another year.", c: "", r: "keikeu"},
    {p: "Calendar", a: "달력", d: "The roadmap to birthdays and deadlines.", c: "", r: "dallyeok"},
    {p: "Canada", a: "캐나다", d: "Where maple syrup flows like water.", c: "", r: "kaenada"},
    {p: "Cat", a: "고양이", d: "The fluffy therapist for lonely hearts.", c: "", r: "goyangi"},
    {p: "Cell phone", a: "휴대전화", d: "The tiny portal to the entire universe.", c: "", r: "hyudaejeonhwa"},
    {p: "Heavy", a: "무거운", d: "The VIP section of things you don't want to carry.", c: "", r: "mugeoun"},
    {p: "Here", a: "여기", d: "The only place GPS can confidently point to.", c: "", r: "yeogi"},
    {p: "Hiking", a: "등산", d: "The scenic route to finding your breath.", c: "", r: "deungsan"},
    {p: "Hometown", a: "고향", d: "The land of childhood memories and awkward haircuts.", c: "", r: "gohyang"},
    {p: "Hot", a: "더운", d: "The default setting of summer.", c: "", r: "deoun"},
    {p: "Hour", a: "시간", d: "The currency of life, spend wisely.", c: "", r: "sigan"},
    {p: "How it is", a: "어떻게 되다", d: "The universal question mark at the end of every plan.", c: "", r: "eotteoke doeda"},
    {p: "Be", a: "되다", d: "The ultimate goal of every 'becoming.'", c: "", r: "doeda"},
    {p: "Beautiful", a: "아름다운", d: "The view that makes your heart skip a beat.", c: "", r: "areumdaun"},
    {p: "Beauty shop", a: "미용실", d: "Where transformations are scheduled and self-esteem is redeemed.", c: "", r: "miyongsil"},
    {p: "Bed", a: "침대", d: "The sanctuary for dreams and Netflix binges.", c: "", r: "chimdae"},
]

const SubSelectionTest = [

]

export {PromptDatabaseSejongVocab as PromptDatabase};