const PromptDatabaseBasic = [
    {p: "Hello", a: "안녕하세요", d: "Standard greeting in Korean.", c: "", r: "annyeonghaseyo"},
    {p: "Thank you", a: "감사합니다", d: "Expressing gratitude in Korean.", c: "", r: "gamsahamnida"},
    {p: "Yes", a: "네", d: "Simple affirmative response.", c: "", r: "ne"},
    {p: "No", a: "아니요", d: "Simple negative response.", c: "", r: "aniyo"},
    {p: "I'm sorry", a: "미안합니다", d: "Apologizing in Korean.", c: "", r: "mianhamnida"},
    {p: "Love", a: "사랑", d: "Expressing affection or deep care.", c: "", r: "sarang"},
    {p: "Friend", a: "친구", d: "Someone with whom one shares a bond of mutual affection.", c: "", r: "chingu"},
    {p: "Bag", a: "가방", d: "Container for carrying personal items.", c: "", r: "gabang"},
    {p: "School", a: "학교", d: "Place of education.", c: "", r: "hakgyo"},
    {p: "Food", a: "음식", d: "General term for sustenance.", c: "", r: "eumsik"},
    {p: "Water", a: "물", d: "Essential liquid for hydration.", c: "", r: "mul"},
    {p: "Coffee", a: "커피", d: "Popular beverage made from roasted coffee beans.", c: "", r: "keopi"},
    {p: "Tea", a: "차", d: "Hot or cold beverage made by infusing dried leaves in water.", c: "", r: "cha"},
    {p: "Apple", a: "사과", d: "Fruit with a red or green skin and crisp white flesh.", c: "", r: "sagwa"},
    {p: "Cat", a: "고양이", d: "Small domesticated carnivorous mammal.", c: "", r: "goyangi"},
    {p: "Dog", a: "개", d: "Domesticated carnivorous mammal.", c: "", r: "gae"},
    {p: "Book", a: "책", d: "Written or printed work consisting of pages.", c: "", r: "chaek"},
    {p: "Time", a: "시간", d: "Indication of when an event occurs.", c: "", r: "sigan"},
    {p: "Weather", a: "날씨", d: "Conditions of the atmosphere at a particular time and place.", c: "", r: "nalssi"},
    {p: "Like", a: "좋아요", d: "Expressing positive feelings or preferences.", c: "", r: "joayo"},
    {p: "Dislike", a: "싫어요", d: "Expressing negative feelings or preferences.", c: "", r: "sireoyo"},
    {p: "Where", a: "어디", d: "Asking about a location or place.", c: "", r: "eodi"},
    {p: "Here", a: "여기", d: "Indicating a location or place near the speaker.", c: "", r: "yeogi"},
    {p: "There", a: "거기", d: "Indicating a location or place near the listener.", c: "", r: "geogi"},
    {p: "When", a: "언제", d: "Asking about a specific time or occasion.", c: "", r: "eonje"},
    {p: "Who", a: "누구", d: "Asking about the identity of a person.", c: "", r: "nugu"},
    {p: "What", a: "뭐", d: "Asking about the identity or nature of something.", c: "", r: "mwo"},
    {p: "Why", a: "왜", d: "Asking for the reason or cause of something.", c: "", r: "wae"},
    {p: "How", a: "어떻게", d: "Asking about the manner or method of doing something.", c: "", r: "eotteoke"},
    {p: "Delicious", a: "맛있어요", d: "Expressing enjoyment of food or drink.", c: "", r: "masisseoyo"},
    {p: "This", a: "이", d: "Indicating something near the speaker.", c: "", r: "i"},
    {p: "That", a: "그", d: "Indicating something near the listener.", c: "", r: "geu"},
    {p: "That (over there)", a: "저", d: "Indicating something far from both speaker and listener.", c: "", r: "jeo"},
    {p: "Beautiful", a: "아름다운", d: "Having beauty or aesthetic appeal.", c: "", r: "areumdaun"},
    {p: "Big", a: "큰", d: "Of considerable size.", c: "", r: "keun"},
    {p: "Small", a: "작은", d: "Of limited size or magnitude.", c: "", r: "jageun"},
    {p: "High", a: "높은", d: "Having a great vertical extent.", c: "", r: "nopheun"},
    {p: "Low", a: "낮은", d: "Having little height.", c: "", r: "nopheun"},
    {p: "New", a: "새", d: "Recently made or created.", c: "", r: "sae"},
    {p: "Old", a: "오래된", d: "Having lived for a long time.", c: "", r: "oraedoen"},
    {p: "Fast", a: "빠른", d: "Moving or capable of moving quickly.", c: "", r: "ppareun"},
    {p: "Slow", a: "느린", d: "Moving or operating at a low speed.", c: "", r: "neurin"},
    {p: "Good", a: "좋은", d: "Having favorable qualities.", c: "", r: "joeun"},
    {p: "Bad", a: "나쁜", d: "Having undesirable or negative qualities.", c: "", r: "nappeun"},
    {p: "Happy", a: "행복한", d: "Feeling or showing pleasure or contentment.", c: "", r: "haengbokhan"},
    {p: "Sad", a: "슬픈", d: "Feeling or showing sorrow or unhappiness.", c: "", r: "seulpeun"},
    {p: "Cold", a: "추운", d: "Having a low temperature.", c: "", r: "chuun"},
    {p: "Hot", a: "더운", d: "Having a high temperature.", c: "", r: "deoun"},
    {p: "Joyful", a: "기쁜", d: "Feeling or expressing joy.", c: "", r: "gippeun"},
    {p: "Sorrowful", a: "슬픈", d: "Feeling or expressing sadness.", c: "", r: "seulpeun"},
    {p: "True", a: "진실한", d: "In accordance with fact or reality.", c: "", r: "jinsilhan"},
    {p: "False", a: "거짓말한", d: "Not in accordance with fact or reality.", c: "", r: "geojitmalhan"},
    {p: "Something", a: "무엇", d: "A thing that is unspecified or unknown.", c: "", r: "mueos"},
    {p: "Nothing", a: "아무것도", d: "Not anything; no single thing.", c: "", r: "amugeotdo"},
    {p: "Everything", a: "모든", d: "All things; all possible options.", c: "", r: "modeun"},
    {p: "Many", a: "많은", d: "A large number or amount of something.", c: "", r: "manheun"},
    {p: "Few", a: "적은", d: "Not many; a small number of something.", c: "", r: "jeogeun"},
    {p: "Easy", a: "쉬운", d: "Not difficult; requiring little effort.", c: "", r: "swiun"},
    {p: "Difficult", a: "어려운", d: "Needing much effort or skill to accomplish.", c: "", r: "eoryeoun"},
    {p: "Near", a: "가까운", d: "Close to in distance or time.", c: "", r: "gakkao-un"},
    {p: "Far", a: "먼", d: "At a great distance from the observer.", c: "", r: "meon"},
    {p: "Yet", a: "아직", d: "Up to the present or a specified time.", c: "", r: "ajik"},
    {p: "Already", a: "이미", d: "Before or by now or the time in question.", c: "", r: "imi"},
    {p: "Now", a: "이제", d: "At the present time or moment.", c: "", r: "ije"},
    {p: "Later", a: "나중에", d: "At a time subsequent to the present or an anticipated event.", c: "", r: "najunge"},
    {p: "Always", a: "항상", d: "At all times; on all occasions.", c: "", r: "hangsang"},
    {p: "Sometimes", a: "종종", d: "On certain occasions or in certain cases but not always.", c: "", r: "jongjong"},
    {p: "Occasionally", a: "가끔", d: "From time to time; now and then.", c: "", r: "gakkeum"},
    {p: "Korea", a: "한국", d: "Country in East Asia.", c: "", r: "hanguk"},
    {p: "America", a: "미국", d: "Country in North America.", c: "", r: "mi-guk"},
    {p: "Japan", a: "일본", d: "Country in East Asia.", c: "", r: "ilbon"},
    {p: "China", a: "중국", d: "Country in East Asia.", c: "", r: "jungguk"},
    {p: "English", a: "영어", d: "West Germanic language widely spoken worldwide.", c: "", r: "yeong-eo"},
    {p: "Korean (language)", a: "한국어", d: "Language spoken in Korea.", c: "", r: "hangugeo"},
    {p: "Chicken", a: "치킨", d: "Popular meat from the domestic fowl.", c: "", r: "chikin"},
    {p: "Homework", a: "숙제", d: "Schoolwork assigned to be done outside the classroom.", c: "", r: "sukje"},
    {p: "Travel", a: "여행", d: "Journeying from one place to another.", c: "", r: "yeohaeng"},
    {p: "Exercise", a: "운동", d: "Physical activity done to maintain health.", c: "", r: "undong"},
    {p: "Weekend", a: "주말", d: "Period of leisure time between the end of the working week and the start of the next.", c: "", r: "jumal"},
    {p: "Movie", a: "영화", d: "Form of entertainment that tells stories through images and sounds.", c: "", r: "yeonghwa"},
    {p: "Music", a: "음악", d: "Art form consisting of sound and silence.", c: "", r: "eumak"},
    {p: "Dance", a: "춤", d: "Series of movements performed to music.", c: "", r: "chum"},
    {p: "Study", a: "공부", d: "The act of acquiring knowledge or skills.", c: "", r: "gongbu"},
    {p: "Shopping", a: "쇼핑", d: "Purchasing goods from stores.", c: "", r: "syoping"},
    {p: "Photo", a: "사진", d: "Image captured by a camera.", c: "", r: "sajin"},
    {p: "Family", a: "가족", d: "Group consisting of parents and their children.", c: "", r: "gajok"},
    {p: "House/Home", a: "집", d: "Building where one lives.", c: "", r: "jip"},
    {p: "Song", a: "노래", d: "Musical composition.", c: "", r: "nolae"},
    {p: "Friends", a: "친구들", d: "Plural form of friend.", c: "", r: "chingu-deul"},
    {p: "Practice", a: "연습", d: "Repetition of an activity to improve skill.", c: "", r: "yeonseup"},
    {p: "Cooking", a: "요리", d: "The practice or skill of preparing food.", c: "", r: "yori"},
    {p: "Vacation", a: "방학", d: "A period of time devoted to leisure.", c: "", r: "banghak"},
    {p: "Park", a: "공원", d: "Public garden or area of land.", c: "", r: "gongwon"},
    {p: "Flower", a: "꽃", d: "The seed-bearing part of a plant.", c: "", r: "kkot"},
    {p: "Color", a: "색", d: "Visual perception.", c: "", r: "saek"},
    {p: "Number", a: "숫자", d: "An arithmetical value.", c: "", r: "sujja"},
    {p: "Animal", a: "동물", d: "Living organism that feeds on organic matter.", c: "", r: "dongmul"},
    {p: "Sound", a: "소리", d: "Vibrations that travel through the air.", c: "", r: "sori"},
    {p: "Problem", a: "문제", d: "A matter or situation regarded as unwelcome or harmful.", c: "", r: "munje"},
    {p: "Answer", a: "답", d: "A solution to a problem or question.", c: "", r: "dap"}
]

const PromptDatabaseWeather = [
    {p: "Sunny", a: "맑다", d: "Bright and clear, perfect for pretending to jog.", c: "", r: "makda"},
    {p: "Raining", a: "비가 오다", d: "The sky is crying because it can't find its umbrella.", c: "와요 (wayo), 왔어요 (wasseoyo), 옵니다 (omnida)", r: "biga oda"},
    {p: "Cloudy", a: "흐리다", d: "When the sky can't decide what to wear.", c: "흐려요 (heuryeoyo), 흐렸어요 (heuryeosseoyo), 흐립니다 (heurimnida)", r: "heurida"},
    {p: "Windy", a: "바람이 불다", d: "Hold onto your hat, or say goodbye to it!", c: "불어요 (bureoyo), 불었어요 (bureosseoyo), 붑니다 (bum nida)", r: "barami bulda"},
    {p: "Snowing", a: "눈이 오다", d: "Time for a snowball fight, or hot cocoa indoors.", c: "와요 (wayo), 왔어요 (wasseoyo), 옵니다 (omnida)", r: "nuni oda"},
    {p: "Hot", a: "덥다", d: "Feels like you're in a microwave.", c: "더워요 (deowoyo), 더웠어요 (deowosseoyo), 덥습니다 (deopseumnida)", r: "deopda"},
    {p: "Cold", a: "춥다", d: "Winter's way of hugging you tightly.", c: "추워요 (chuwoyo), 추웠어요 (chuwosseoyo), 춥습니다 (chupseumnida)", r: "chupda"},
    {p: "Humid", a: "습하다", d: "Like walking through a wet sponge.", c: "습해요 (seuphaeyo), 습했어요 (seuphaesseoyo), 습합니다 (seuphamnida)", r: "seupada"},
    {p: "Clear", a: "맑음", d: "No clouds, no excuses to stay inside.", c: "", r: "malgeum"},
    {p: "Foggy", a: "안개 끼다", d: "The world in soft focus, just like a dream.", c: "껴요 (kkyeoyo), 꼈어요 (kkyeosseoyo), 낍니다 (kkimnida)", r: "angae kkida"},
    {p: "Stormy", a: "폭풍우가 치다", d: "Thunder and lightning: nature's drum solo.", c: "쳐요 (chyeoyo), 쳤어요 (chyeosseoyo), 칩니다 (ch imnida)", r: "pokpunguga chida"},
    {p: "Cool", a: "시원하다", d: "A breeze that feels like air conditioning.", c: "시원해요 (siwonhaeyo), 시원했어요 (siwonhaesseoyo), 시원합니다 (siwonhamnida)", r: "siwonhada"},
    {p: "Freezing", a: "얼다", d: "Colder than your ex's heart.", c: "얼어요 (eoreoyo), 얼었어요 (eoreosseoyo), 얼습니다 (eorseumnida)", r: "eolda"},
    {p: "Breezy", a: "바람이 솔솔", d: "Gentle wind that messes up your hair.", c: "", r: "barami solsol"},
    {p: "Mild", a: "온화하다", d: "Just right, Goldilocks would approve.", c: "온화해요 (onhwahaeyo), 온화했어요 (onhwahaesseoyo), 온화합니다 (onhwaham nida)", r: "onhwahada"},
    {p: "Rainy", a: "비오는", d: "Perfect for Netflix and chill (literally).", c: "", r: "bioneun"},
    {p: "Icy", a: "얼음이 끼다", d: "Slippery like a banana peel in a cartoon.", c: "껴요 (kkyeoyo), 꼈어요 (kkyeosseoyo), 낍니다 (kkimnida)", r: "eoreumi kkida"},
    {p: "Wet", a: "젖다", d: "Feels like you forgot your umbrella again.", c: "젖어요 (jeojeoyo), 젖었어요 (jeojeosseoyo), 젖습니다 (jeotseumnida)", r: "jeotda"},
    {p: "Dry", a: "건조하다", d: "No moisture, just like your jokes.", c: "건조해요 (geonjohaeyo), 건조했어요 (geonjohaesseoyo), 건조합니다 (geonjohamnida)", r: "geonjohada"},
    {p: "Chilly", a: "쌀쌀하다", d: "A bit too cold, like a passive-aggressive comment.", c: "쌀쌀해요 (ssalssalhaeyo), 쌀쌀했어요 (ssalssalhaesseoyo), 쌀쌀합니다 (ssalssalhamnida)", r: "ssalssalhada"},
    {p: "Drizzling", a: "이슬비가 내리다", d: "Light rain, the sky's just sprinkling.", c: "내려요 (naeryeoyo), 내렸어요 (naeryeosseoyo), 내립니다 (naer imnida)", r: "iseulbiga naerida"},
    {p: "Snowstorm", a: "눈보라", d: "Heavy snow and strong winds, brace yourself!", c: "", r: "nunbora"},
    {p: "Blustery", a: "바람이 많이 불다", d: "Wind strong enough to steal your hat.", c: "불어요 (bureoyo), 불었어요 (bureosseoyo), 붑니다 (bumnida)", r: "barami mani bulda"},
    {p: "Overcast", a: "구름이 많다", d: "Gray skies make everything look like a moody film.", c: "많아요 (manhayo), 많았어요 (manhasseoyo), 많습니다 (manhseumnida)", r: "gureumi manta"},
    {p: "Thunder", a: "천둥이 치다", d: "Nature's way of saying, 'Turn down the volume!'", c: "쳐요 (chyeoyo), 쳤어요 (chyeosseoyo), 칩니다 (ch imnida)", r: "cheondungi chida"}    
]

const PromptDatabaseRestaurant = [
    {p: "Menu", a: "메뉴", d: "Your roadmap to deliciousness.", c: "", r: "menyu"},
    {p: "Order", a: "주문하다", d: "How to make food appear magically.", c: "주문해요 (jumunhaeyo), 주문했어요 (jumunhaesseoyo), 주문합니다 (jumunhamnida)", r: "jumunhada"},
    {p: "Waiter", a: "웨이터", d: "Your new best friend for the next hour.", c: "", r: "weiteo"},
    {p: "Bill", a: "계산서", d: "The part you don't want to see.", c: "", r: "gyesanseo"},
    {p: "Water", a: "물", d: "Because hydration is key.", c: "", r: "mul"},
    {p: "Delicious", a: "맛있다", d: "What you hope everything tastes like.", c: "맛있어요 (masisseoyo), 맛있었어요 (masisseosseoyo), 맛있습니다 (masitseumnida)", r: "masitda"},
    {p: "Spicy", a: "맵다", d: "When your tongue feels on fire.", c: "매워요 (maewoyo), 매웠어요 (maewosseoyo), 맵습니다 (maepseumnida)", r: "maepda"},
    {p: "Table", a: "테이블", d: "Where the magic happens.", c: "", r: "teibeul"},
    {p: "Soup", a: "수프", d: "Liquid comfort in a bowl.", c: "", r: "supeu"},
    {p: "Rice", a: "밥", d: "The staple of every meal.", c: "", r: "bap"},
    {p: "Side dish", a: "반찬", d: "The supporting cast to your main dish.", c: "", r: "banchan"},
    {p: "Chopsticks", a: "젓가락", d: "Mastery required for full enjoyment.", c: "", r: "jeotgarak"},
    {p: "Fork", a: "포크", d: "Your trusty western friend.", c: "", r: "pokeu"},
    {p: "Chicken", a: "치킨", d: "The universal comfort food.", c: "", r: "chikin"},
    {p: "Beef", a: "소고기", d: "The king of meats.", c: "", r: "sogogi"},
    {p: "Vegetables", a: "야채", d: "The healthy stuff your mom insists on.", c: "", r: "yachae"},
    {p: "Pork", a: "돼지고기", d: "The meat that makes bacon.", c: "", r: "dwaejigogi"},
    {p: "Fish", a: "생선", d: "The one that swims before it grills.", c: "", r: "saengseon"},
    {p: "To eat", a: "먹다", d: "The whole point of this adventure.", c: "먹어요 (meogeoyo), 먹었어요 (meogeosseoyo), 먹습니다 (meokseumnida)", r: "meokda"},
    {p: "To drink", a: "마시다", d: "Because you need a beverage with that.", c: "마셔요 (masyeoyo), 마셨어요 (masyeosseoyo), 마십니다 (masimnida)", r: "masida"},
    {p: "Restaurant", a: "식당", d: "The place where the food magic happens.", c: "", r: "sikdang"},
    {p: "Tea", a: "차", d: "The drink that soothes and energizes.", c: "", r: "cha"},
    {p: "Coffee", a: "커피", d: "Your liquid fuel.", c: "", r: "keopi"},
    {p: "Dessert", a: "디저트", d: "The sweet end to a good meal.", c: "", r: "dijeoteu"},
    {p: "Reservation", a: "예약", d: "Ensures you have a spot at the table.", c: "", r: "yeyak"}

]

const PromptDatabaseSejongVocab = [
    {p: "Engagement", a: "약혼", d: "The official start of 'We're in this together' club.", c: "", r: "yakhon"},
    {p: "Vocabulary", a: "어휘", d: "The stuff you pretend to know during a test.", c: "", r: "eohwi"},
    {p: "Index", a: "색인", d: "A list of excuses for not reading the whole book.", c: "", r: "saegin"},
    {p: "Chilly", a: "추운", d: "When your fridge gets jealous of the outdoors.", c: "", r: "chuun"},
    {p: "China", a: "중국", d: "Where all your ceramic mugs come from.", c: "", r: "jungguk"},
    {p: "Class", a: "수업", d: "A place where sleep is just a blink away.", c: "", r: "sueob"},
    {p: "Every day", a: "매일", d: "The one thing that always happens, every single day.", c: "", r: "maeil"},
    {p: "Exercise", a: "운동", d: "The art of convincing yourself to sweat.", c: "", r: "undong"},
    {p: "Classroom", a: "교실", d: "Where the real drama happens, besides K-dramas.", c: "", r: "gyosil"},
    {p: "Clean", a: "깨끗한", d: "What your room becomes when guests are expected.", c: "", r: "kkaekkeuthan"},
    {p: "Clock", a: "시계", d: "A device that has a grudge against procrastination.", c: "", r: "sigye"},
    {p: "Clothes", a: "옷", d: "Things you wear to pretend you have your life together.", c: "", r: "ot"},
    {p: "Cloudy", a: "흐린", d: "The sky's version of 'I'm not in the mood.'", c: "", r: "heurin"},
    {p: "Coffee", a: "커피", d: "The liquid that turns 'leave me alone' into 'good morning.'", c: "", r: "keopi"},
    {p: "Cold", a: "추운", d: "Nature's way of telling you to snuggle up.", c: "", r: "chuun"},
    {p: "College student", a: "대학생", d: "The sleep-deprived species known for surviving on ramen.", c: "", r: "daehaksaeng"},
    {p: "Come", a: "오다", d: "When plans finally decide to show up.", c: "", r: "oda"},
    {p: "Commute", a: "통근", d: "The daily race against time and traffic.", c: "", r: "tonggeun"},
    {p: "Company", a: "회사", d: "Where your weekdays go to feel productive.", c: "", r: "hoesa"},
    {p: "Computer", a: "컴퓨터", d: "The modern-day magic box for all your procrastination needs.", c: "", r: "keompyuteo"},
    {p: "Concert", a: "콘서트", d: "Where music turns strangers into a chorus.", c: "", r: "konseoteu"},
    {p: "Content", a: "내용", d: "The reason you scrolled all the way down.", c: "", r: "naeyong"},
    {p: "Convenience store", a: "편의점", d: "The saving grace at 2 AM when hunger strikes.", c: "", r: "pyeonuijeom"},
    {p: "Cook", a: "요리사", d: "The wizard behind the kitchen curtains.", c: "", r: "yorisa"},
    {p: "Fall", a: "가을", d: "When nature decides to redecorate in warm hues.", c: "", r: "gaeul"},
    {p: "Father", a: "아버지", d: "The OG dad jokes supplier.", c: "", r: "abeoji"},
    {p: "February", a: "2월", d: "The shortest month with the biggest Valentine's bill.", c: "", r: "iyweol"},
    {p: "Fifteen", a: "십오", d: "The age of confusion between being a kid and a teenager.", c: "", r: "sip-o"},
    {p: "Fifty", a: "오십", d: "When life begins at 50, and so does the fun.", c: "", r: "osip"},
    {p: "Fishing", a: "낚시", d: "The art of fooling fish into thinking you're a friend.", c: "", r: "naksi"},
    {p: "Alphabetical order", a: "알파벳 순서", d: "The library's way of keeping chaos in check.", c: "", r: "alpabes sunseo"},
    {p: "Floor", a: "바닥", d: "The unsung hero of our daily adventures.", c: "", r: "badak"},
    {p: "Flower", a: "꽃", d: "Nature's way of saying 'smile, it's free.'", c: "", r: "kkot"},
    {p: "Food", a: "음식", d: "The reason you go to a restaurant instead of the gym.", c: "", r: "eumsik"},
    {p: "Forty", a: "사십", d: "When you realize life's just getting started at 40.", c: "", r: "sasip"},
    {p: "Four seasons", a: "사계절", d: "Nature's wardrobe change, four times a year.", c: "", r: "sagyejeol"},
    {p: "Four", a: "사", d: "The number of fingers we use for counting.", c: "", r: "sa"},
    {p: "Fourteen", a: "십사", d: "The age of 'almost there, but not quite.'", c: "", r: "sipsa"},
    {p: "France", a: "프랑스", d: "Where cheese and wine have a romantic rendezvous.", c: "", r: "peurangseu"},
    {p: "Friend", a: "친구", d: "The personal cheerleader in life's marathon.", c: "", r: "chingu"},
    {p: "Fruit", a: "과일", d: "Nature's sweet rebellion against junk food.", c: "", r: "gwail"},
    {p: "Fun", a: "재미있는", d: "The excuse you use for procrastination.", c: "", r: "jaemiinneun"},
    {p: "Gear", a: "장비", d: "The superhero outfit for your hobbies.", c: "", r: "jangbi"},
    {p: "Cool", a: "시원한", d: "The official temperature of chill vibes.", c: "", r: "siwonhan"},
    {p: "Cosmetics", a: "화장품", d: "The magic wand for the 8 AM transformation.", c: "", r: "hwajangpum"},
    {p: "Country", a: "나라", d: "Where patriotism and passport meet.", c: "", r: "nara"},
    {p: "Begin", a: "시작하다", d: "The moment when 'someday' becomes 'today.'", c: "", r: "sijakhada"},
    {p: "Behind", a: "뒤에", d: "Where surprises and shadows lurk.", c: "", r: "dwie"},
    {p: "Between", a: "사이에", d: "The space where decisions hang in the balance.", c: "", r: "saie"},
    {p: "Beverage", a: "음료", d: "Liquid courage in a cup.", c: "", r: "eumryo"},
    {p: "Bicycle", a: "자전거", d: "The two-wheeled escape from traffic.", c: "", r: "jajeongeo"},
    {p: "Birthday", a: "생일", d: "The annual reminder of your 'specialness.'", c: "", r: "saengil"},
    {p: "Blackboard", a: "칠판", d: "Where dust meets wisdom.", c: "", r: "chilpan"},
    {p: "Blow", a: "불다", d: "The human version of wind power.", c: "", r: "bunda"},
    {p: "Book", a: "책", d: "The ultimate time machine.", c: "", r: "chaek"},
    {p: "Bottle", a: "병", d: "The ship that carries your liquid treasure.", c: "", r: "byeong"},
    {p: "Boy", a: "소년", d: "A human whirlwind of mischief and wonder.", c: "", r: "sonyeon"},
    {p: "Bread", a: "빵", d: "The edible hug that fits in your hand.", c: "", r: "ppang"},
    {p: "Bulgogi", a: "불고기", d: "The Korean BBQ that converts vegetarians.", c: "", r: "bulgogi"},
    {p: "Bus", a: "버스", d: "The mobile waiting room for life's adventures.", c: "", r: "beoseu"},
    {p: "Busan", a: "부산", d: "Where seafood and sea breezes reign supreme.", c: "", r: "busan"},
    {p: "Business", a: "비즈니스", d: "The adult version of playing house.", c: "", r: "bijeuniseu"},
    {p: "A little", a: "조금", d: "The portion size that never satisfies.", c: "", r: "jogeum"},
    {p: "A lot", a: "많이", d: "The serving size that always surprises.", c: "", r: "manhi"},
    {p: "Activity", a: "활동", d: "The organized chaos of being productive.", c: "", r: "hwaldong"},
    {p: "Address", a: "주소", d: "Where GPS and hope intersect.", c: "", r: "juso"},
    {p: "Afternoon", a: "오후", d: "The siesta before the second wind kicks in.", c: "", r: "ohu"},
    {p: "All", a: "모두", d: "The elusive concept of 'everyone.'", c: "", r: "modu"},
    {p: "Amusement park", a: "놀이 공원", d: "Where gravity takes a vacation.", c: "", r: "noli gongwon"},
    {p: "Cup", a: "컵", d: "The vessel that holds your morning sanity.", c: "", r: "keop"},
    {p: "Date", a: "날짜", d: "The tiny reminder of your existence on the timeline.", c: "", r: "nalja"},
    {p: "Day", a: "일", d: "The unit of time you try to fit a lifetime into.", c: "", r: "il"},
    {p: "December", a: "12월", d: "When holiday spirit meets shopping frenzy.", c: "", r: "sibweol"},
    {p: "Department store", a: "백화점", d: "The labyrinth where wallets go to die.", c: "", r: "baekhwajeom"},
    {p: "Desk", a: "책상", d: "The island of productivity in the sea of chaos.", c: "", r: "chaeksang"},
    {p: "Different", a: "다른", d: "The spice of life's smorgasbord.", c: "", r: "dareun"},
    {p: "Difficult", a: "어려운", d: "The VIP section of life's obstacle course.", c: "", r: "eoryeoun"},
    {p: "Do", a: "하다", d: "The universal solution to procrastination.", c: "", r: "hada"},
    {p: "Doctor", a: "의사", d: "The human repair shop.", c: "", r: "uisa"},
    {p: "Drink", a: "마시다", d: "The liquid version of 'I got this.'", c: "", r: "masida"},
    {p: "And", a: "그리고", d: "The glue that holds sentences together.", c: "", r: "geurigo"},
    {p: "Answer", a: "대답", d: "The whisper in the silence of questions.", c: "", r: "daedap"},
    {p: "Apple", a: "사과", d: "The forbidden fruit that keeps the doctor busy.", c: "", r: "sagwa"},
    {p: "Appointment", a: "약속", d: "Where time and commitment shake hands.", c: "", r: "yaksok"},
    {p: "April", a: "4월", d: "When pranks and showers are in season.", c: "", r: "sawol"},
    {p: "August", a: "8월", d: "When summer's lease is almost up.", c: "", r: "palweol"},
    {p: "Autumn foliage", a: "가을 단풍", d: "Nature's canvas of warm hues.", c: "", r: "gaeul danpung"},
    {p: "Busy", a: "바쁜", d: "The badge of honor for the overcommitted.", c: "", r: "bappeun"},
    {p: "Bag", a: "가방", d: "The portable universe for all your stuff.", c: "", r: "gabang"},
    {p: "Ball", a: "공", d: "The roundest way to make friends.", c: "", r: "gong"},
    {p: "Banana", a: "바나나", d: "Nature's original snack pack.", c: "", r: "banana"},
    {p: "Basement", a: "지하실", d: "Where spiders and forgotten treasures reside.", c: "", r: "jihasil"},
    {p: "Basketball", a: "농구", d: "The symphony of hoops and dreams.", c: "", r: "nonggu"},
    {p: "But", a: "하지만", d: "The bridge between 'yes' and 'no.'", c: "", r: "hajiman"},
    {p: "Buy", a: "사다", d: "The adult version of 'treat yo'self.'", c: "", r: "sada"},
    {p: "Café", a: "카페", d: "The fueling station for caffeine and gossip.", c: "", r: "kafe"},
    {p: "Cake", a: "케이크", d: "The sweet reward for surviving another year.", c: "", r: "keikeu"},
    {p: "Calendar", a: "달력", d: "The roadmap to birthdays and deadlines.", c: "", r: "dallyeok"},
    {p: "Canada", a: "캐나다", d: "Where maple syrup flows like water.", c: "", r: "kaenada"},
    {p: "Cat", a: "고양이", d: "The fluffy therapist for lonely hearts.", c: "", r: "goyangi"},
    {p: "Cell phone", a: "휴대전화", d: "The tiny portal to the entire universe.", c: "", r: "hyudaejeonhwa"},
    {p: "Heavy", a: "무거운", d: "The VIP section of things you don't want to carry.", c: "", r: "mugeoun"},
    {p: "Here", a: "여기", d: "The only place GPS can confidently point to.", c: "", r: "yeogi"},
    {p: "Hiking", a: "등산", d: "The scenic route to finding your breath.", c: "", r: "deungsan"},
    {p: "Hometown", a: "고향", d: "The land of childhood memories and awkward haircuts.", c: "", r: "gohyang"},
    {p: "Hot", a: "더운", d: "The default setting of summer.", c: "", r: "deoun"},
    {p: "Hour", a: "시간", d: "The currency of life, spend wisely.", c: "", r: "sigan"},
    {p: "How it is", a: "어떻게 되다", d: "The universal question mark at the end of every plan.", c: "", r: "eotteoke doeda"},
    {p: "Be", a: "되다", d: "The ultimate goal of every 'becoming.'", c: "", r: "doeda"},
    {p: "Beautiful", a: "아름다운", d: "The view that makes your heart skip a beat.", c: "", r: "areumdaun"},
    {p: "Beauty shop", a: "미용실", d: "Where transformations are scheduled and self-esteem is redeemed.", c: "", r: "miyongsil"},
    {p: "Bed", a: "침대", d: "The sanctuary for dreams and Netflix binges.", c: "", r: "chimdae"},
    {p: "Pen", a: "펜", d: "The ink-stained wizard of words.", c: "", r: "pen"},
    {p: "Case", a: "케이스", d: "The chameleon of protection and style.", c: "", r: "keiseu"},
    {p: "Person", a: "사람", d: "The puzzle piece in life's mosaic.", c: "", r: "saram"},
    {p: "Phone number", a: "전화번호", d: "The digital fingerprint of communication.", c: "", r: "jeonhwabeonho"},
    {p: "Photo", a: "사진", d: "The pause button on memories.", c: "", r: "sajin"},
    {p: "Piano", a: "피아노", d: "The maestro of melody and melancholy.", c: "", r: "piano"},
    {p: "Piece", a: "조각", d: "The breadcrumbs of a bigger picture.", c: "", r: "jogak"},
    {p: "Pizza", a: "피자", d: "The edible frisbee of happiness.", c: "", r: "pija"},
    {p: "Place", a: "장소", d: "The stage where memories take their bow.", c: "", r: "jangso"},
    {p: "Special", a: "특별한", d: "The VIP pass to life's extraordinary moments.", c: "", r: "teukbyeolhan"},
    {p: "Spicy", a: "매운", d: "The fire alarm for taste buds.", c: "", r: "maeun"},
    {p: "Spring", a: "봄", d: "The season of hope and floral confetti.", c: "", r: "bom"},
    {p: "Store", a: "가게", d: "The treasure trove of wants and needs.", c: "", r: "gage"},
    {p: "Strawberry", a: "딸기", d: "The heart-shaped jewel of summer.", c: "", r: "ttalgi"},
    {p: "Student", a: "학생", d: "The scholar in training, armed with curiosity.", c: "", r: "haksaeng"},
    {p: "Study", a: "공부", d: "The marathon of mind muscles.", c: "", r: "gongbu"},
    {p: "Summer", a: "여름", d: "The season of sun-kissed adventures.", c: "", r: "yeoreum"},
    {p: "Swim", a: "수영하다", d: "The aquatic ballet of buoyancy and grace.", c: "", r: "suyeonghada"},
    {p: "Play", a: "놀다", d: "The recess from adulting.", c: "", r: "nolda"},
    {p: "Please", a: "부탁드리다", d: "The magic word for unlocking favors.", c: "", r: "butagdeurida"},
    {p: "Swimming pool", a: "수영장", d: "The liquid playground of aquanauts.", c: "", r: "suyeongjang"},
    {p: "Police officer", a: "경찰관", d: "The unsung hero of public safety.", c: "", r: "gyeongchalgwan"},
    {p: "Pretty", a: "예쁜", d: "The aesthetic eye candy.", c: "", r: "yeppeun"},
    {p: "Swimming", a: "수영", d: "The splashy symphony of strokes.", c: "", r: "suyeong"},
    {p: "Sydney", a: "시드니", d: "Where kangaroos hop and accents charm.", c: "", r: "sidinei"},
    {p: "Word", a: "단어", d: "The building blocks of babel.", c: "", r: "dan-eo"},
    {p: "Number", a: "숫자", d: "The breadcrumbs of mathematics.", c: "", r: "sujja"},
    {p: "Rain", a: "비", d: "The tap dance of nature's tears.", c: "", r: "bi"},
    {p: "Taekwondo", a: "태권도", d: "The martial art of kicking and discipline.", c: "", r: "taegweondo"},
    {p: "Ramyeon", a: "라면", d: "The midnight snack of champions.", c: "", r: "ramyeon"},
    {p: "Take", a: "가지다", d: "The choose-your-own-adventure button.", c: "", r: "gajida"},
    {p: "Read", a: "읽다", d: "The magic carpet ride for imagination.", c: "", r: "ikda"},
    {p: "Tasty", a: "맛있는", d: "The standing ovation for flavor.", c: "", r: "masissneun"},
    {p: "Really", a: "진짜", d: "The truth serum of exclamations.", c: "", r: "jinjja"},
    {p: "Tea", a: "차", d: "The warm hug in a cup.", c: "", r: "cha"},
    {p: "Recently", a: "최근에", d: "The newsflash in life's timeline.", c: "", r: "choegune"},
    {p: "Teacher", a: "선생님", d: "The mentor shaping futures one lesson at a time.", c: "", r: "seonsaengnim"},
    {p: "Rest", a: "휴식", d: "The siesta for the soul.", c: "", r: "hyusik"},
    {p: "Television", a: "텔레비전", d: "The living room oracle.", c: "", r: "tellebijyeon"},
    {p: "Restaurant", a: "레스토랑", d: "The culinary oasis of cravings and cuisine.", c: "", r: "reseutorang"},
    {p: "Ten", a: "십", d: "The hand with fingers all accounted for.", c: "", r: "sip"},
    {p: "Ride", a: "타다", d: "The rollercoaster of transportation.", c: "", r: "tada"},
    {p: "Thank", a: "감사하다", d: "The bouquet of gratitude.", c: "", r: "gamsahada"},
    {p: "That", a: "그", d: "The pointing finger of specificity.", c: "", r: "geu"},
    {p: "Then", a: "그럼", d: "The segue to the next scene.", c: "", r: "geuleom"},
    {p: "There", a: "거기", d: "The X marks the spot.", c: "", r: "geogi"},
    {p: "Thing", a: "것", d: "The mystery box of the mundane.", c: "", r: "geos"},
    {p: "Thirteen", a: "십삼", d: "The awkward tween of numbers.", c: "", r: "sipsam"},
    {p: "Thirty", a: "삼십", d: "The countdown to life's halftime show.", c: "", r: "samsip"},
    {p: "This", a: "이", d: "The universal pointer of proximity.", c: "", r: "i"},
    {p: "Three", a: "삼", d: "The trio of musketeers.", c: "", r: "sam"},
    {p: "Time", a: "시간", d: "The sand in life's hourglass.", c: "", r: "sigan"},
    {p: "Today", a: "오늘", d: "The present unwrapped daily.", c: "", r: "oneul"},
    {p: "Together", a: "함께", d: "The harmonious melody of unity.", c: "", r: "hamkke"},
    {p: "Tomorrow", a: "내일", d: "The sequel to today's story.", c: "", r: "naeil"},
    {p: "Toothbrush", a: "칫솔", d: "The superhero of oral hygiene.", c: "", r: "chitsol"},
    {p: "Toothpaste", a: "치약", d: "The minty defender of smiles.", c: "", r: "chiyak"},
    {p: "Town", a: "마을", d: "The nest of neighbors and nostalgia.", c: "", r: "maeul"},
    {p: "Travel", a: "여행", d: "The passport to new horizons and heartbeats.", c: "", r: "yeohaeng"},
    {p: "TV drama", a: "드라마", d: "The emotional rollercoaster of pixels and plots.", c: "", r: "deurama"},
    {p: "Twelve", a: "십이", d: "The year's final chapter.", c: "", r: "sip-i"},
    {p: "Room", a: "방", d: "The sanctuary of solitude or socializing.", c: "", r: "bang"},
    {p: "Russia", a: "러시아", d: "The land of matryoshka and mysteries.", c: "", r: "reosia"},
    {p: "School break", a: "방학", d: "The recess from academia.", c: "", r: "banghag"},
    {p: "School", a: "학교", d: "The playground of knowledge and friendships.", c: "", r: "hakgyo"},
    {p: "Sea", a: "바다", d: "The cradle of whispers and waves.", c: "", r: "bada"},
    {p: "Season", a: "계절", d: "The chameleon of nature's wardrobe.", c: "", r: "gyejeol"},
    {p: "See", a: "보다", d: "The gaze that paints memories.", c: "", r: "boda"},
    {p: "Seoul", a: "서울", d: "The bustling heart of South Korea.", c: "", r: "seoul"},
    {p: "September", a: "9월", d: "The month of transitions and transformations.", c: "", r: "guweol"},
    {p: "Seven", a: "칠", d: "The roll of the dice, lucky or otherwise.", c: "", r: "chil"},
    {p: "Seventeen", a: "열일곱", d: "The teenage whirlwind of rebellion and romance.", c: "", r: "yeol-ilgop"},
    {p: "Seventy", a: "칠십", d: "The odometer of life's journey.", c: "", r: "chilsip"},
    {p: "Sheet", a: "시트", d: "The canvas of comfort and cocoon.", c: "", r: "siteu"},
    {p: "Shoes", a: "신발", d: "The stepping stones of style and stride.", c: "", r: "sinbal"},
    {p: "Shopping mall", a: "쇼핑몰", d: "The labyrinth of wants and window displays.", c: "", r: "syopingmol"},
    {p: "Shopping", a: "쇼핑", d: "The therapy session for shopaholics.", c: "", r: "syoping"},
    {p: "Singer", a: "가수", d: "The voice of a generation.", c: "", r: "gasu"},
    {p: "Sit", a: "앉다", d: "The pause button on motion.", c: "", r: "anjda"},
    {p: "Six", a: "육", d: "The half-dozen of numerology.", c: "", r: "yug"},
    {p: "Sixteen", a: "열여섯", d: "The sweet sixteen of adolescence.", c: "", r: "yeolyeoseos"},
    {p: "Sixty", a: "육십", d: "The golden jubilee of life's odometer.", c: "", r: "yugsip"},
    {p: "Sleep", a: "자다", d: "The nightly voyage to dreamland.", c: "", r: "jada"},
    {p: "Snack", a: "간식", d: "The appetizer of life's feast.", c: "", r: "gansik"},
    {p: "How much", a: "얼마나", d: "The ultimate question mark on every shopping spree.", c: "", r: "eolmana"},
    {p: "However", a: "그러나", d: "The plot twist in life's screenplay.", c: "", r: "geureona"},
    {p: "Meeting", a: "회의", d: "Where good intentions and long agendas collide.", c: "", r: "hoeui"},
    {p: "Milk", a: "우유", d: "The liquid breakfast for champions.", c: "", r: "uyu"},
    {p: "Minute", a: "분", d: "The tiny sliver of eternity.", c: "", r: "bun"},
    {p: "Month", a: "달", d: "The moon's way of keeping track of time.", c: "", r: "dal"},
    {p: "Mood", a: "기분", d: "The emotional weather report.", c: "", r: "gibun"},
    {p: "Morning", a: "아침", d: "The dawn of hope and caffeine.", c: "", r: "achim"},
    {p: "Ice cream", a: "아이스크림", d: "The cure for a bad day in a cone.", c: "", r: "aiseukeurim"},
    {p: "In front of", a: "앞에", d: "The stage where anticipation takes the spotlight.", c: "", r: "ape"},
    {p: "Indonesia", a: "인도네시아", d: "Where islands and smiles meet.", c: "", r: "indonesia"},
    {p: "Inside", a: "안에", d: "The cozy confines of your comfort zone.", c: "", r: "ane"},
    {p: "Internet café", a: "인터넷 카페", d: "Where coffee fuels gaming quests.", c: "", r: "inteoneseu kape"},
    {p: "Moscow", a: "모스크바", d: "Where winters are long and history is rich.", c: "", r: "moseukuba"},
    {p: "Mother", a: "어머니", d: "The queen of multitasking and unconditional love.", c: "", r: "eomeoni"},
    {p: "Movie theater", a: "영화관", d: "Where popcorn and dreams collide.", c: "", r: "yeonghwagwan"},
    {p: "Movie", a: "영화", d: "The escape hatch from reality.", c: "", r: "yeonghwa"},
    {p: "Mr./Ms./Miss", a: "씨/아가씨", d: "The mystery title that comes before a name.", c: "", r: "ssi/agassi"},
    {p: "Museum", a: "박물관", d: "Where history whispers and artifacts shout.", c: "", r: "bagmulgwan"},
    {p: "Jakarta", a: "자카르타", d: "Where traffic jams and street food reign.", c: "", r: "jakareuta"},
    {p: "January", a: "1월", d: "When resolutions are made and broken.", c: "", r: "ilweol"},
    {p: "Japan", a: "일본", d: "Where tradition and technology walk hand in hand.", c: "", r: "ilbon"},
    {p: "Jeju-do", a: "제주도", d: "Where beaches and tangerines embrace.", c: "", r: "jejudo"},
    {p: "Job", a: "일", d: "The adult version of 'what do you want to be when you grow up?'", c: "", r: "il"},
    {p: "Juice", a: "주스", d: "The fruit's last hurrah before the blender.", c: "", r: "juseu"},
    {p: "June", a: "6월", d: "When summer days stretch into forever.", c: "", r: "yukweol"},
    {p: "Music", a: "음악", d: "The soundtrack of your life's montage.", c: "", r: "eumak"},
    {p: "My", a: "나의", d: "The possessive pronoun that's all about you.", c: "", r: "naui"},
    {p: "Name", a: "이름", d: "The label you answer to.", c: "", r: "ireum"},
    {p: "Next to", a: "옆에", d: "The land of 'almost there.'", c: "", r: "yeope"},
    {p: "Nine", a: "아홉", d: "When counting feels like playing hide and seek.", c: "", r: "ahop"},
    {p: "Nineteen", a: "십구", d: "The age of 'in-between.'", c: "", r: "sipgu"},
    {p: "Ninety", a: "구십", d: "When experience comes with a side of wisdom.", c: "", r: "gusip"},
    {p: "No", a: "아니", d: "The shortest sentence with the most meaning.", c: "", r: "ani"},
    {p: "Not be", a: "아니다", d: "The answer to 'are we there yet?'", c: "", r: "anida"},
    {p: "Note", a: "메모", d: "The breadcrumbs of memory.", c: "", r: "memo"},
    {p: "November", a: "11월", d: "When autumn whispers goodbye.", c: "", r: "sibileol"},
    {p: "Now", a: "지금", d: "The only moment that matters.", c: "", r: "jigeum"},
    {p: "Number", a: "숫자", d: "The breadcrumbs of mathematics.", c: "", r: "sujja"},
    {p: "Karaoke", a: "노래방", d: "Where stars are born and eardrums go to retire.", c: "", r: "noraebang"},
    {p: "Kenya", a: "케냐", d: "Where savannas and safaris beckon.", c: "", r: "kenya"},
    {p: "Kimchi", a: "김치", d: "The spicy sidekick to every Korean meal.", c: "", r: "kimchi"},
    {p: "King Sejong Institute", a: "세종학당", d: "Where language dreams take flight.", c: "", r: "sejonghakdang"},
    {p: "Korea", a: "한국", d: "Where tradition and modernity dance.", c: "", r: "hanguk"},
    {p: "Korean language", a: "한국어", d: "The bridge to a thousand-year culture.", c: "", r: "hangugeo"},
    {p: "KPOP", a: "케이팝", d: "The global beat of youth culture.", c: "", r: "keipap"},
    {p: "Learn", a: "배우다", d: "The journey from ignorance to enlightenment.", c: "", r: "baeuda"},
    {p: "Left", a: "왼쪽", d: "The direction of the heart's compass.", c: "", r: "oenjjok"},
    {p: "Library", a: "도서관", d: "Where whispers echo and knowledge slumbers.", c: "", r: "doseogwan"},
    {p: "Light", a: "빛", d: "The brushstroke of dawn on darkness's canvas.", c: "", r: "bit"},
    {p: "Like", a: "좋아하다", d: "The universal button for 'yes, please.'", c: "", r: "joahada"},
    {p: "Listen", a: "듣다", d: "The silent applause for someone's voice.", c: "", r: "deutda"},
    {p: "Look around", a: "둘러보다", d: "The first step in every adventure.", c: "", r: "dulleoboda"},
    {p: "Love", a: "사랑", d: "The gravity that holds hearts together.", c: "", r: "sarang"},
    {p: "Lunch", a: "점심", d: "The midday oasis in the desert of hunger.", c: "", r: "jeomsim"},
    {p: "October", a: "10월", d: "When leaves bid farewell to trees.", c: "", r: "sipweol"},
    {p: "Office worker", a: "직장인", d: "The hero of 9 to 5 adventures.", c: "", r: "jigjangin"},
    {p: "Often", a: "자주", d: "The frequent flyer in life's itinerary.", c: "", r: "jaju"},
    {p: "Older brother", a: "형", d: "The keeper of secrets and hand-me-downs.", c: "", r: "hyeong"},
    {p: "Older sister", a: "누나", d: "The first best friend and fashion consultant.", c: "", r: "nuna"},
    {p: "On top of", a: "위에", d: "The pedestal of hierarchy and chaos.", c: "", r: "wie"},
    {p: "One hundred", a: "백", d: "The numerical milestone on the road to infinity.", c: "", r: "baek"},
    {p: "Make", a: "만들다", d: "The artist's journey from blank canvas to masterpiece.", c: "", r: "mandeulda"},
    {p: "March", a: "3월", d: "When winter bids farewell and spring tiptoes in.", c: "", r: "samweol"},
    {p: "Mari", a: "마리", d: "The friendly unit of animal companionship.", c: "", r: "mari"},
    {p: "One", a: "하나", d: "The loneliest number, but never alone.", c: "", r: "hana"},
    {p: "Open", a: "열다", d: "The invitation to new adventures and old memories.", c: "", r: "yeolda"},
    {p: "Other", a: "다른", d: "The flip side of 'same.'", c: "", r: "dareun"},
    {p: "Our", a: "우리", d: "The collective embrace of togetherness.", c: "", r: "uri"},
    {p: "Outside", a: "밖", d: "The playground of nature's wild side.", c: "", r: "bak"},
    {p: "The number of", a: "수", d: "The magic word that unlocks mathematical mysteries.", c: "", r: "su"},
    {p: "Mart", a: "마트", d: "Where shopping lists come to life.", c: "", r: "mateu"},
    {p: "Matter", a: "문제", d: "The puzzle piece in life's jigsaw.", c: "", r: "munje"},
    {p: "May", a: "5월", d: "When flowers bloom and dreams awaken.", c: "", r: "owol"},
    {p: "Meal", a: "식사", d: "The communion of sustenance and conversation.", c: "", r: "siksa"},
    {p: "Meet", a: "만나다", d: "The reunion of souls across time and space.", c: "", r: "mannada"},
    {p: "Page", a: "페이지", d: "The window into worlds beyond.", c: "", r: "peiji"},
    {p: "Park", a: "공원", d: "The sanctuary of serenity in the urban jungle.", c: "", r: "gongwon"},
    {p: "Part-time job", a: "알바", d: "The rite of passage into adulting.", c: "", r: "alba"},
    {p: "Party", a: "파티", d: "The celebration of life's milestones and Monday blues.", c: "", r: "pati"},
]

const SubSelectionTest = [

]

export {PromptDatabaseSejongVocab as PromptDatabase};
export {PromptDatabaseWeather as weatherDatabase};
export {PromptDatabaseRestaurant as restaurantDatabase};