const PromptDatabase = [
    {p: "Hello", a: "안녕하세요", d: "Standard greeting in Korean.", c: "", r: "annyeonghaseyo"},
    {p: "Thank you", a: "감사합니다", d: "Expressing gratitude in Korean.", c: "", r: "gamsahamnida"},
    {p: "Yes", a: "네", d: "Simple affirmative response.", c: "", r: "ne"},
    {p: "No", a: "아니요", d: "Simple negative response.", c: "", r: "aniyo"},
    {p: "I'm sorry", a: "미안합니다", d: "Apologizing in Korean.", c: "", r: "mianhamnida"},
    {p: "Love", a: "사랑", d: "Expressing affection or deep care.", c: "", r: "sarang"},
    {p: "Friend", a: "친구", d: "Someone with whom one shares a bond of mutual affection.", c: "", r: "chingu"},
    {p: "Bag", a: "가방", d: "Container for carrying personal items.", c: "", r: "gabang"},
    {p: "School", a: "학교", d: "Place of education.", c: "", r: "hakgyo"},
    {p: "Food", a: "음식", d: "General term for sustenance.", c: "", r: "eumsik"},
    {p: "Water", a: "물", d: "Essential liquid for hydration.", c: "", r: "mul"},
    {p: "Coffee", a: "커피", d: "Popular beverage made from roasted coffee beans.", c: "", r: "keopi"},
    {p: "Tea", a: "차", d: "Hot or cold beverage made by infusing dried leaves in water.", c: "", r: "cha"},
    {p: "Apple", a: "사과", d: "Fruit with a red or green skin and crisp white flesh.", c: "", r: "sagwa"},
    {p: "Cat", a: "고양이", d: "Small domesticated carnivorous mammal.", c: "", r: "goyangi"},
    {p: "Dog", a: "개", d: "Domesticated carnivorous mammal.", c: "", r: "gae"},
    {p: "Book", a: "책", d: "Written or printed work consisting of pages.", c: "", r: "chaek"},
    {p: "Time", a: "시간", d: "Indication of when an event occurs.", c: "", r: "sigan"},
    {p: "Weather", a: "날씨", d: "Conditions of the atmosphere at a particular time and place.", c: "", r: "nalssi"},
    {p: "Like", a: "좋아요", d: "Expressing positive feelings or preferences.", c: "", r: "joayo"},
    {p: "Dislike", a: "싫어요", d: "Expressing negative feelings or preferences.", c: "", r: "sireoyo"},
    {p: "Where", a: "어디", d: "Asking about a location or place.", c: "", r: "eodi"},
    {p: "Here", a: "여기", d: "Indicating a location or place near the speaker.", c: "", r: "yeogi"},
    {p: "There", a: "거기", d: "Indicating a location or place near the listener.", c: "", r: "geogi"},
    {p: "When", a: "언제", d: "Asking about a specific time or occasion.", c: "", r: "eonje"},
    {p: "Who", a: "누구", d: "Asking about the identity of a person.", c: "", r: "nugu"},
    {p: "What", a: "뭐", d: "Asking about the identity or nature of something.", c: "", r: "mwo"},
    {p: "Why", a: "왜", d: "Asking for the reason or cause of something.", c: "", r: "wae"},
    {p: "How", a: "어떻게", d: "Asking about the manner or method of doing something.", c: "", r: "eotteoke"},
    {p: "Delicious", a: "맛있어요", d: "Expressing enjoyment of food or drink.", c: "", r: "masisseoyo"},
    {p: "This", a: "이", d: "Indicating something near the speaker.", c: "", r: "i"},
    {p: "That", a: "그", d: "Indicating something near the listener.", c: "", r: "geu"},
    {p: "That (over there)", a: "저", d: "Indicating something far from both speaker and listener.", c: "", r: "jeo"},
    {p: "Beautiful", a: "아름다운", d: "Having beauty or aesthetic appeal.", c: "", r: "areumdaun"},
    {p: "Big", a: "큰", d: "Of considerable size.", c: "", r: "keun"},
    {p: "Small", a: "작은", d: "Of limited size or magnitude.", c: "", r: "jageun"},
    {p: "High", a: "높은", d: "Having a great vertical extent.", c: "", r: "nopheun"},
    {p: "Low", a: "낮은", d: "Having little height.", c: "", r: "nopheun"},
    {p: "New", a: "새", d: "Recently made or created.", c: "", r: "sae"},
    {p: "Old", a: "오래된", d: "Having lived for a long time.", c: "", r: "oraedoen"},
    {p: "Fast", a: "빠른", d: "Moving or capable of moving quickly.", c: "", r: "ppareun"},
    {p: "Slow", a: "느린", d: "Moving or operating at a low speed.", c: "", r: "neurin"},
    {p: "Good", a: "좋은", d: "Having favorable qualities.", c: "", r: "joeun"},
    {p: "Bad", a: "나쁜", d: "Having undesirable or negative qualities.", c: "", r: "nappeun"},
    {p: "Happy", a: "행복한", d: "Feeling or showing pleasure or contentment.", c: "", r: "haengbokhan"},
    {p: "Sad", a: "슬픈", d: "Feeling or showing sorrow or unhappiness.", c: "", r: "seulpeun"},
    {p: "Cold", a: "추운", d: "Having a low temperature.", c: "", r: "chuun"},
    {p: "Hot", a: "더운", d: "Having a high temperature.", c: "", r: "deoun"},
    {p: "Joyful", a: "기쁜", d: "Feeling or expressing joy.", c: "", r: "gippeun"},
    {p: "Sorrowful", a: "슬픈", d: "Feeling or expressing sadness.", c: "", r: "seulpeun"},
    {p: "True", a: "진실한", d: "In accordance with fact or reality.", c: "", r: "jinsilhan"},
    {p: "False", a: "거짓말한", d: "Not in accordance with fact or reality.", c: "", r: "geojitmalhan"},
    {p: "Something", a: "무엇", d: "A thing that is unspecified or unknown.", c: "", r: "mueos"},
    {p: "Nothing", a: "아무것도", d: "Not anything; no single thing.", c: "", r: "amugeotdo"},
    {p: "Everything", a: "모든", d: "All things; all possible options.", c: "", r: "modeun"},
    {p: "Many", a: "많은", d: "A large number or amount of something.", c: "", r: "manheun"},
    {p: "Few", a: "적은", d: "Not many; a small number of something.", c: "", r: "jeogeun"},
    {p: "Easy", a: "쉬운", d: "Not difficult; requiring little effort.", c: "", r: "swiun"},
    {p: "Difficult", a: "어려운", d: "Needing much effort or skill to accomplish.", c: "", r: "eoryeoun"},
    {p: "Near", a: "가까운", d: "Close to in distance or time.", c: "", r: "gakkao-un"},
    {p: "Far", a: "먼", d: "At a great distance from the observer.", c: "", r: "meon"},
    {p: "Yet", a: "아직", d: "Up to the present or a specified time.", c: "", r: "ajik"},
    {p: "Already", a: "이미", d: "Before or by now or the time in question.", c: "", r: "imi"},
    {p: "Now", a: "이제", d: "At the present time or moment.", c: "", r: "ije"},
    {p: "Later", a: "나중에", d: "At a time subsequent to the present or an anticipated event.", c: "", r: "najunge"},
    {p: "Always", a: "항상", d: "At all times; on all occasions.", c: "", r: "hangsang"},
    {p: "Sometimes", a: "종종", d: "On certain occasions or in certain cases but not always.", c: "", r: "jongjong"},
    {p: "Occasionally", a: "가끔", d: "From time to time; now and then.", c: "", r: "gakkeum"},
    {p: "Korea", a: "한국", d: "Country in East Asia.", c: "", r: "hanguk"},
    {p: "America", a: "미국", d: "Country in North America.", c: "", r: "mi-guk"},
    {p: "Japan", a: "일본", d: "Country in East Asia.", c: "", r: "ilbon"},
    {p: "China", a: "중국", d: "Country in East Asia.", c: "", r: "jungguk"},
    {p: "English", a: "영어", d: "West Germanic language widely spoken worldwide.", c: "", r: "yeong-eo"},
    {p: "Korean (language)", a: "한국어", d: "Language spoken in Korea.", c: "", r: "hangugeo"},
    {p: "Chicken", a: "치킨", d: "Popular meat from the domestic fowl.", c: "", r: "chikin"},
    {p: "Homework", a: "숙제", d: "Schoolwork assigned to be done outside the classroom.", c: "", r: "sukje"},
    {p: "Travel", a: "여행", d: "Journeying from one place to another.", c: "", r: "yeohaeng"},
    {p: "Exercise", a: "운동", d: "Physical activity done to maintain health.", c: "", r: "undong"},
    {p: "Weekend", a: "주말", d: "Period of leisure time between the end of the working week and the start of the next.", c: "", r: "jumal"},
    {p: "Movie", a: "영화", d: "Form of entertainment that tells stories through images and sounds.", c: "", r: "yeonghwa"},
    {p: "Music", a: "음악", d: "Art form consisting of sound and silence.", c: "", r: "eumak"},
    {p: "Dance", a: "춤", d: "Series of movements performed to music.", c: "", r: "chum"},
    {p: "Study", a: "공부", d: "The act of acquiring knowledge or skills.", c: "", r: "gongbu"},
    {p: "Shopping", a: "쇼핑", d: "Purchasing goods from stores.", c: "", r: "syoping"},
    {p: "Photo", a: "사진", d: "Image captured by a camera.", c: "", r: "sajin"},
    {p: "Family", a: "가족", d: "Group consisting of parents and their children.", c: "", r: "gajok"},
    {p: "House/Home", a: "집", d: "Building where one lives.", c: "", r: "jip"},
    {p: "Song", a: "노래", d: "Musical composition.", c: "", r: "nolae"},
    {p: "Friends", a: "친구들", d: "Plural form of friend.", c: "", r: "chingu-deul"},
    {p: "Practice", a: "연습", d: "Repetition of an activity to improve skill.", c: "", r: "yeonseup"},
    {p: "Cooking", a: "요리", d: "The practice or skill of preparing food.", c: "", r: "yori"},
    {p: "Vacation", a: "방학", d: "A period of time devoted to leisure.", c: "", r: "banghak"},
    {p: "Park", a: "공원", d: "Public garden or area of land.", c: "", r: "gongwon"},
    {p: "Flower", a: "꽃", d: "The seed-bearing part of a plant.", c: "", r: "kkot"},
    {p: "Color", a: "색", d: "Visual perception.", c: "", r: "saek"},
    {p: "Number", a: "숫자", d: "An arithmetical value.", c: "", r: "sujja"},
    {p: "Animal", a: "동물", d: "Living organism that feeds on organic matter.", c: "", r: "dongmul"},
    {p: "Sound", a: "소리", d: "Vibrations that travel through the air.", c: "", r: "sori"},
    {p: "Problem", a: "문제", d: "A matter or situation regarded as unwelcome or harmful.", c: "", r: "munje"},
    {p: "Answer", a: "답", d: "A solution to a problem or question.", c: "", r: "dap"}
]

const SubSelectionTest = [

]

export {PromptDatabase};